name: Build-Docker-Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: docker.pkg.github.com
      VERSION: 1.0.${{github.run_number}}
      DOCKER_REPOSITORY: docker.pkg.github.com/ricardani/aws-cloudformation-demo-fe/aws-demo-fe

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: 'Install dependencies'
      run: npm ci

    - name: 'Build application'
      run: npm run build

    - name: 'Build docker image and publish it to github packages'
      run: |
        docker login -u ${{github.actor}} -p ${{secrets.GITHUB_TOKEN}} ${{env.DOCKER_REGISTRY}}
        docker build -t ${{env.DOCKER_REPOSITORY}}:${{env.VERSION}} .
        docker push ${{env.DOCKER_REPOSITORY}}:${{env.VERSION}}
